# Generated by Django 5.1.4 on 2024-12-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(choices=[('MIC18', 'MIC18'), ('MIC20', 'MIC20'), ('MIC23', 'MIC23')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('CIV', 'Civil'), ('AID', 'Artificial Intelligence'), ('AIM', 'Artificial Intelligence & ML'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MTECH', 'M.Tech')], max_length=50)),
                ('semester', models.CharField(choices=[('SEM1', 'Semester 1'), ('SEM2', 'Semester 2'), ('SEM3', 'Semester 3'), ('SEM4', 'Semester 4'), ('SEM5', 'Semester 5'), ('SEM6', 'Semester 6'), ('SEM7', 'Semester 7'), ('SEM8', 'Semester 8')], max_length=10)),
                ('pdf', models.FileField(upload_to='semester_notes/')),
            ],
        ),
    ]
