# Generated by Django 5.1.4 on 2024-12-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesternote',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='semesternote',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('CIV', 'Civil'), ('AID', 'Artificial Intelligence and DS'), ('AIM', 'Artificial Intelligence & ML'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MTECH', 'M.Tech')], max_length=50),
        ),
    ]
